'''
Author: Minh Long Vu
Date: 
Application: This file store all the worker classes
'''


import queue
import threading
import torch
from faster_whisper import WhisperModel
from ollama import chat
from src.chat_classes import *
from kokoro.model import KModel
from misaki import en
import msvcrt
import sounddevice as sd

def flush_input():
    
    '''
    flush_input(): This function is used to clean the buffering.    
    
    return: no return
    '''
    
    while msvcrt.kbhit():
            msvcrt.getch()


def get_sentence(message:str):
    
    '''
    get_setence(): This function is used to split between complete setences and partial setence.
    
    message: the message that need to be cut
    
    return: a falg if there is complete sentence, a partial sentence and a complete setence
    '''
    
    index_Dot = message.find(".")
    isDot = False if index_Dot == -1 else True
    partial_sentence= ''
    complete_sentence= ''
    if isDot == False:
        partial_sentence=message
        complete_sentence=None
    else:
        if isDot == len(message) - 1:
            partial_sentence=''
            complete_sentence=message
        else:
            partial_sentence = message[index_Dot+1:]
            # include the dot
            complete_sentence = message[:index_Dot+1]
    return isDot, partial_sentence, complete_sentence


def chat_worker(root: Root, 
                chat_queue: queue.Queue,
                user: Chat,
                bot: Chat):
    
    '''
    chat_worker():  This function frequently read from chat queue and 
    send it to the root. The reason why it is not a thread because the 
    tkinter has some problems with thread and it demand to be in the main thread.
    
    root: The GUI of chat box
    chat_queue: The queue that store message for the GUI
    user: The user who send the prompt
    bot: The AI respond 
    
    return: no return
    '''
    try:
        while True:
            # .get() should only use for threads not main progra
            (role,chat) = chat_queue.get_nowait()
            if role == "user":
                user.create_chat(chat)
            elif role == "bot":
                bot.create_chat(chat)
    except:
        # if empty it raise exception
        root.get_root().after(100, chat_worker, root, chat_queue, user, bot)


def tts_worker(kokoro_model: KModel, 
               g2p: en.G2P,
               voice:torch.load,
               sentence_queue:queue.Queue, 
               audio_queue:queue.Queue):
    
    '''
    tts_worker(): Create a thread that convert sentence from the sentence queue
    to the audio array and send it to audio queue.
    
    kokoro_model: Convert phoneme to audio array
    g2p: convert from sentence (grapheme) to IPA (phoneme)
    voice: the type of voice that we want to hear.
    sentence_queue: The queue that store text sentence for the tts
    audio_queue: The queue that store audio array for the speaker
    
    return: no return
    '''
    
    
    while True:
        sentence_emoji = sentence_queue.get()
        sentence_emoji_split = sentence_emoji.split("/")
        sentence = sentence_emoji_split[0]
        # codecs.decode(sentence_emoji[1], 'unicode_escape')
        
        phonemes,_ = g2p(sentence)
        with torch.inference_mode():
            output = kokoro_model(phonemes,voice[len(phonemes)-1],1,return_output=True)
        audio_queue.put(output.audio)
        sentence_queue.task_done()
        
        


def pa_worker(audio_queue: queue.Queue,
              mic_ready: threading.Event,
              last_sentence_event: threading.Event):
    
    
    '''
    pa_worker(): Create a thread that play the audio from the audio queue
    
    audio_queue: THe queue that store audio array for the speaker
    mic_ready: an threading event to set when the mic should be ready
    last_sentence_event: event to check if the last sentence was generated by the language model
    
    return: no return
    '''
    
    with sd.OutputStream(samplerate=24000, channels=1, dtype='float32', blocksize=0, latency='low') as stream:
  
        while True:
            audio_data = audio_queue.get()
            stream.write(audio_data)
            audio_queue.task_done()
            if last_sentence_event.is_set() and audio_queue.empty():
                print("last sentence")
                last_sentence_event.clear()
                mic_ready.set()

def prompt_worker(model_name:str,
                  prompt_queue: queue.Queue,
                  chat_queue: queue.Queue,
                  sentence_queue: queue.Queue,
                  audio_queue: queue.Queue,
                  last_sentence_event: threading.Event,
                  mic_ready: threading.Event):
    
    '''
    prompt_worker(): Create a thread that read text from prompt queue
    and send that prompt to the model. Then it send full sentence to 
    the sentence queue
    
    model_name: The name of the model
    prompt_queue: The queue that store speech from the user
    chat_queue: The queue that store the chat for GUI
    sentence_queue: The queue that store a complete sentence
    audio_queue: The queue that store the audio array for speaker 
    last_sentence_event: event to check if the last sentence was 
    generated by the language model
    mic_ready: an threading event to set when the mic should be ready
    
    return: no return 
    '''
    
    
    while True:
        prompt = prompt_queue.get()
        mic_ready.clear()
        print("Get prompt")
        
        if len(prompt.strip()) == 0:
            mic_ready.set()
            continue
    
        
        stream_chat = chat(
            model=model_name,
            messages=[{'role':'user','content': f"{prompt}"}],
            stream=True
        )
        chat_queue.put(("user",prompt))
        print(f"Prompt: {prompt}")
        print("Answer: ")
        sentence = ""
        for chunk in stream_chat:
            if chunk.message.content:
                
                sentence += chunk.message.content 
                isDot, sentence, completed_sentence = get_sentence(sentence)
                
                if isDot:
                    sentence_queue.put(completed_sentence.strip())
                    chat_queue.put(("bot",completed_sentence.replace("/", "")))
        
        if sentence.strip():
            sentence_queue.put(sentence.strip())
            chat_queue.put(("bot",sentence.replace("/", "")))
            
        last_sentence_event.set()
        sentence_queue.join()
        audio_queue.join()
        
def transcribe_worker(recording_queue: queue.Queue,
                      prompt_queue: queue.Queue,
                      whisper_model: WhisperModel):
    
    '''
    transcribe_worker(): Create a thread that transcribe from the a 
    potential speech from the Voice Activity Detection
    
    recording_queue: The queue that store potential speech from the VAD
    prompt_queue: The queue store the potential transcribed speech for the prompt worker
    whisper_model: The Model that transcribe audio
    
    return: no return
    '''
    
    while True:
        # wait nont-block
        recording = recording_queue.get()
        if len(recording) > 0:
            
            segments, info = whisper_model.transcribe(recording,"en")
            sentence = ""
            for segment in segments:
                sentence += segment.text
            prompt_queue.put(sentence)


def warmup_worker(g2p: en.G2P,
                  kokoro_model: KModel,
                  voice: torch.load):
    
    '''
    warmup_worker(): this function is used to warm up the kokoro model. This would reduce the significant latency of the first prompt
    due to loading
    
    g2p: convert from sentence (grapheme) to IPA (phoneme)
    kokoro_model: Convert phoneme to audio array
    voice: the type of voice that we want to hear.
    
    return: no return
    '''
    
    warmup_text1 = "Warmup pipeline initialized."
    warmup_text2 = "Artificial intelligence is changing how we interact with applications every day."
    try:
        warmup_phonemes1, _ = g2p(warmup_text1)
        warmup_phonemes2,_ = g2p(warmup_text2)
        with torch.inference_mode():
            # This triggers the 1-second compilation step safely in the background
            _ = kokoro_model(warmup_phonemes1, voice[len(warmup_phonemes1)-1], 1, return_output=True)
            _ = kokoro_model(warmup_phonemes2, voice[len(warmup_phonemes2)-1], 1, return_output=True)
        
        print("GPU Warmup Complete. Operational pipeline ready.")
    except Exception as e:
        print(f"[Warning during Warmup]: {e}. Continuing anyway.")
                 